import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TamboProvider } from "@tambo-ai/react";
import { tamboComponents } from "@/lib/tambo-components";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const apiKey = process.env.NEXT_PUBLIC_TAMBO_API_KEY || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TamboProvider apiKey={apiKey} components={tamboComponents}>
          {children}
        </TamboProvider>
      </body>
    </html>
  );
}
